//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemCustomers.SRProjectCompanies {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectCompanies", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrarySystemCompanies.DataCont" +
        "racts")]
    [System.SerializableAttribute()]
    public partial class ProjectCompanies : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateFinishProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateStartProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscriptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateFinishProject {
            get {
                return this.DateFinishProjectField;
            }
            set {
                if ((this.DateFinishProjectField.Equals(value) != true)) {
                    this.DateFinishProjectField = value;
                    this.RaisePropertyChanged("DateFinishProject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateStartProject {
            get {
                return this.DateStartProjectField;
            }
            set {
                if ((this.DateStartProjectField.Equals(value) != true)) {
                    this.DateStartProjectField = value;
                    this.RaisePropertyChanged("DateStartProject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Discriptions {
            get {
                return this.DiscriptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscriptionsField, value) != true)) {
                    this.DiscriptionsField = value;
                    this.RaisePropertyChanged("Discriptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCompany {
            get {
                return this.IdCompanyField;
            }
            set {
                if ((this.IdCompanyField.Equals(value) != true)) {
                    this.IdCompanyField = value;
                    this.RaisePropertyChanged("IdCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProject {
            get {
                return this.IdProjectField;
            }
            set {
                if ((this.IdProjectField.Equals(value) != true)) {
                    this.IdProjectField = value;
                    this.RaisePropertyChanged("IdProject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paid {
            get {
                return this.PaidField;
            }
            set {
                if ((object.ReferenceEquals(this.PaidField, value) != true)) {
                    this.PaidField = value;
                    this.RaisePropertyChanged("Paid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceType {
            get {
                return this.PriceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceTypeField, value) != true)) {
                    this.PriceTypeField = value;
                    this.RaisePropertyChanged("PriceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRProjectCompanies.IProjectCompaniesServices")]
    public interface IProjectCompaniesServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectCompaniesServices/Insert", ReplyAction="http://tempuri.org/IProjectCompaniesServices/InsertResponse")]
        void Insert(SystemCustomers.SRProjectCompanies.ProjectCompanies projectCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectCompaniesServices/Update", ReplyAction="http://tempuri.org/IProjectCompaniesServices/UpdateResponse")]
        void Update(SystemCustomers.SRProjectCompanies.ProjectCompanies projectCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectCompaniesServices/GetAllProjectToCompany", ReplyAction="http://tempuri.org/IProjectCompaniesServices/GetAllProjectToCompanyResponse")]
        string GetAllProjectToCompany();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectCompaniesServices/GetDestination", ReplyAction="http://tempuri.org/IProjectCompaniesServices/GetDestinationResponse")]
        string[] GetDestination();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectCompaniesServices/GetOldDestination", ReplyAction="http://tempuri.org/IProjectCompaniesServices/GetOldDestinationResponse")]
        string GetOldDestination(SystemCustomers.SRProjectCompanies.ProjectCompanies projectCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectCompaniesServices/Delete", ReplyAction="http://tempuri.org/IProjectCompaniesServices/DeleteResponse")]
        void Delete(SystemCustomers.SRProjectCompanies.ProjectCompanies projectCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectCompaniesServices/CheckProjectToCompany", ReplyAction="http://tempuri.org/IProjectCompaniesServices/CheckProjectToCompanyResponse")]
        bool CheckProjectToCompany(SystemCustomers.SRProjectCompanies.ProjectCompanies projectCompany);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectCompaniesServicesChannel : SystemCustomers.SRProjectCompanies.IProjectCompaniesServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectCompaniesServicesClient : System.ServiceModel.ClientBase<SystemCustomers.SRProjectCompanies.IProjectCompaniesServices>, SystemCustomers.SRProjectCompanies.IProjectCompaniesServices {
        
        public ProjectCompaniesServicesClient() {
        }
        
        public ProjectCompaniesServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectCompaniesServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectCompaniesServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectCompaniesServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Insert(SystemCustomers.SRProjectCompanies.ProjectCompanies projectCompany) {
            base.Channel.Insert(projectCompany);
        }
        
        public void Update(SystemCustomers.SRProjectCompanies.ProjectCompanies projectCompany) {
            base.Channel.Update(projectCompany);
        }
        
        public string GetAllProjectToCompany() {
            return base.Channel.GetAllProjectToCompany();
        }
        
        public string[] GetDestination() {
            return base.Channel.GetDestination();
        }
        
        public string GetOldDestination(SystemCustomers.SRProjectCompanies.ProjectCompanies projectCompany) {
            return base.Channel.GetOldDestination(projectCompany);
        }
        
        public void Delete(SystemCustomers.SRProjectCompanies.ProjectCompanies projectCompany) {
            base.Channel.Delete(projectCompany);
        }
        
        public bool CheckProjectToCompany(SystemCustomers.SRProjectCompanies.ProjectCompanies projectCompany) {
            return base.Channel.CheckProjectToCompany(projectCompany);
        }
    }
}
